[SmartBits] Minor fixes
phanrahan/magma pull request #1167
Opened 2022-10-21 22:18 UTC by rsetaluri

2022-10-21 23:22 UTC, leonardt requested changes
We should add some tests to cover these

2022-10-26 21:14 UTC, rsetaluri commented
> We should add some tests to cover these

Done

2022-10-27 01:23 UTC, leonardt commented on magma/smart/smart_bits.py
> +        return SmartBinaryOp(operator.xor, self, other)
Is there a test covering xor?

2022-10-27 14:14 UTC, rsetaluri commented on magma/smart/smart_bits.py
> +        return SmartBinaryOp(operator.xor, self, other)
done

2022-10-28 00:25 UTC, leonardt approved these changes

2022-10-28 00:25 UTC, merged