[when] Temporary Guard Against ALWCOMBORDER issue
phanrahan/magma pull request #1249
Opened 2023-03-21 20:39 UTC by leonardt

See https://github.com/phanrahan/magma/issues/1248 for context, adds a pass that checks whether this issue would be possible and raises an exception.

Ideally we'd support the ok version of this which is when the variable in the loop is assigned before it is used, but this requires some more complex analysis which we can add incrementally (it's also a significant step towards a more general solution that manages these dependencies).

2023-03-23 16:39 UTC, rsetaluri commented
Let's squash all these commits and rebase and force-push. Otherwise the merged and squashed PR's commit message will be pretty messy

2023-03-23 16:42 UTC, rsetaluri reviewed
Is it possible to have this pass run on the magma representation independent of MLIR? It seems like a general pass on circuits with when.

2023-03-23 16:43 UTC, rsetaluri commented
> Is it possible to have this pass run on the magma representation independent of MLIR? it seems like a general pass on the representation



> Is it possible to have this pass run on the magma representation independent of MLIR? it seems like a general pass on the representation?



> Is it possible to have this pass run on the magma representation independent of MLIR? it seems like a general pass on circuits with when

It's possible that the graph view is actually also more general, and can be used as a type of pass.

2023-03-23 16:48 UTC, rsetaluri commented
> Is it possible to have this pass run on the magma representation independent of MLIR? It seems like a general pass on circuits with when.

It's possible that the graph view we're using for the MLIR backend is actually a generally useful representation for passes. We could extract it out and have this check run on that graph.

2023-03-23 17:14 UTC, leonardt commented
I do think the graph logic can and should be generic, but

1. this check is specific to the MLIR backend because that's where there's a problem with compilation
2. this is temporary until compilation is fixed

So I'd advocate for not blocking it by the refactoring of the graph logic, which could seems like an orthogonal change to the issue being addressed.

2023-03-27 19:39 UTC, rsetaluri commented
> 1. this check is specific to the MLIR backend because that's where there's a problem with compilation
It seems like this *could* cause problems with *any* backend?  That is to say, it represents a mismatch in our translation to Verilog more generally?

> 2. this is temporary until compilation is fixed
> 
> So I'd advocate for not blocking it by the refactoring of the graph logic, which could seems like an orthogonal change to the issue being addressed.
Fine with this.

2023-03-27 19:46 UTC, rsetaluri requested changes

2023-03-27 19:46 UTC, rsetaluri commented on magma/backend/mlir/build_magma_graph.py
> +    _check_no_when_loops(ctx.graph)
note need a special subclass of `MlirCompilerError` (in `magma/backend/mlir/errors.py`) called `MlirWhenCycleError` (maybe better phrasing is needed :D )

```suggestion
def _check_for_when_cycles(graph: Graph):
    """Temporary guard against https://github.com/phanrahan/magma/issues/1248."""
    for node in graph.nodes():
        if not is_when_builder(node):
            continue
        for predecessor in graph.predecessors(node):
            if isinstance(type(node), Register):  # cycles are broken by registers
                break
            if predecessor is node:
                raise MlirWhenCycleError()


def build_magma_graph(
        ckt: DefineCircuitKind,
        opts: BuildMagmaGrahOpts = BuildMagmaGrahOpts()) -> Graph:
    ctx = ModuleContext(Graph(), opts)
    _visit_inputs(ctx, ckt, opts.flatten_all_tuples)
    for inst in ckt.instances:
        _visit_inputs(ctx, inst, opts.flatten_all_tuples)
    _check_for_when_cycles(ctx.graph)
```

2023-03-27 19:46 UTC, rsetaluri commented on magma/primitives/when.py
> +        self._set_definition_attr("_is_when_builder_", True)
let's add a separate free function `is_when_builder` which is just `def is_when_builder(obj) -> bool: return getattr(obj, "_is_when_builder_", False)`

can also additionally abstract `"_is_when_builder_"` key into `_IS_WHEN_BUILDER_KEY` constant at the top.

2023-03-27 19:46 UTC, rsetaluri commented on tests/test_when.py
> +    # TODO(leonardt): Remove this when proper analysis is added
nit
```suggestion
    # TODO(leonardt): Remove this when proper analysis for when cycles is added.
```

2023-03-27 19:46 UTC, rsetaluri commented on tests/test_when.py
> +    with pytest.raises(NotImplementedError):
will need to change this error

2023-03-27 19:46 UTC, rsetaluri commented on tests/test_when.py
> +    class test_when_alwcomb_order(m.Circuit):
nit
```suggestion
def test_when_alwcomb_order():

    class test_when_alwcomb_order(m.Circuit):
```

2023-03-27 19:46 UTC, rsetaluri commented on tests/test_when.py
> +                  output="mlir")
```suggestion
        m.compile(
            "build/test_when_alwcomb_order",
            test_when_alwcomb_order,
            output="mlir"
        )
```

2023-03-30 17:47 UTC, rsetaluri approved these changes

2023-03-30 22:16 UTC, merged