Extend set_index for N-D Arrays
phanrahan/magma pull request #1330
Opened 2023-09-26 07:23 UTC by rkshthrmsh

- Add suppport for N-dimensional indices.
- Add more information to assertion messages.

2023-09-26 21:11 UTC, rsetaluri requested changes

2023-09-26 21:11 UTC, rsetaluri commented on magma/primitives/set_index.py
> +from typing import Union, List
```suggestion
from collections.abc import Sequence
from typing import Union

from magma.bits import UInt
from magma.bitutils import clog2
from magma.primitives import mux
```

2023-09-26 21:11 UTC, rsetaluri commented on magma/primitives/set_index.py
> +def set_index(target: Array, value, idx: Union[UInt, List[UInt]]):
```suggestion
def set_index(target: Array, value, idx: Union[UInt, Sequence[UInt]]):
```

2023-09-26 21:11 UTC, rsetaluri commented on magma/primitives/set_index.py
> +    * `target` - a value of type `Array[N, T]` or `Array[(N, M, ..), T]`
```suggestion
    * `target` - a value of type `Array[N, T]` or `Array[(N, M, L, ...), T]`
```

2023-09-26 21:11 UTC, rsetaluri commented on magma/primitives/set_index.py
> +    * `idx` - a value of type `UInt[clog2(N)]` or `[UInt[clog2(M)], UInt[clog2(N)], ..]`
```suggestion
    * `idx` - a value of type `UInt[clog2(N)]` or `(UInt[clog2(L)], UInt[clog2(M), UInt[clog2(N)], ...)`
```

2023-09-26 21:11 UTC, rsetaluri commented on magma/primitives/set_index.py
> +    More details: https://github.com/phanrahan/magma/issues/1310
```suggestion
    NOTE(rkshthrmsh): Ordering of indices in `idx` is reverse of ordering in N-D Array definition.
    For more details see: https://github.com/phanrahan/magma/issues/1310.
```

2023-09-26 21:11 UTC, rsetaluri commented on magma/primitives/set_index.py
> +        raise TypeError(f"Expected `idx` ({type(idx)}) to be UInt or List[UInt, ...] ")
Let's flip these

```suggestion
    if isinstance(idx, UInt):
        target_T = type(target)
        if not isinstance(value, target_T.T):
            raise TypeError(
                f"Expected `value` ({type(value)}) to be the same type as"
                f"`target`'s contents ({target_T.T})"
            )
        if not isinstance(idx, UInt):
            raise TypeError("Expected `idx` ({type(idx)}) to be a UInt")
        if len(idx) != clog2(len(target_T)):
            raise TypeError(
                f"Expected number of `idx` ({len(idx)}) bits to map to the length of"
                f"`target` ({clog2(len(target_T))})")
            )
        return target_T([
            mux([elem, value], idx == i) for i, elem in enumerate(target)
        ])
    if isinstance(idx, Sequence):
        if len(idx) == 1:
            return set_index(target, value, idx[0])
        return set_index(target, set_index(target[idx[0]], value, idx[1:]), idx[0])
    raise TypeError(f"Expected `idx` ({type(idx)}) to be UInt or List[UInt, ...] ")
```

2023-09-27 03:54 UTC, rkshthrmsh commented
@rsetaluri, I have committed all the suggestions. Thanks!

2023-10-11 08:10 UTC, rkshthrmsh commented
@rsetaluri, I have made the necessary changes to the test file. However, I'm unable to run it because `pip install fault` fails with:
```
 ERROR: Failed building wheel for coreir
  Building wheel for DeCiDa (pyproject.toml) ... done
  Created wheel for DeCiDa: filename=DeCiDa-1.1.5-py3-none-any.whl size=13947008 sha256=8dda2758409edef16994bd393ab64c3e7f6e25e80a597367ac0f1fb4a18f0595
  Stored in directory: /Users/rkshthrmsh/Library/Caches/pip/wheels/64/21/c3/f58e97f65bdac62c9ac1e98711dc44d30300e8801a4eccc2f8
Successfully built fault DeCiDa
Failed to build coreir
ERROR: Could not build wheels for coreir, which is required to install pyproject.toml-based projects
```

How can I get around this?

2023-10-30 05:21 UTC, rkshthrmsh commented
@rsetaluri, added test for N-D `set_index()`

2024-01-10 11:15 UTC, rkshthrmsh commented
@rsetaluri / @leonardt, any update on this PR?

2024-01-13 00:47 UTC, leonardt approved these changes

2024-01-13 00:48 UTC, leonardt commented
@rkshthrmsh can you either merge or rebase on the latest master just to make sure it's working with the latest head?

2024-03-04 03:36 UTC, rkshthrmsh commented
Closing this as it is merged in #1353

2024-03-04 03:36 UTC, closed without merging